import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { X, Search, UserPlus } from 'lucide-react';
export function AssignAgentModal({ selectedCount, users, currentAgentId, onAssign, onClose, }) {
    const [search, setSearch] = useState('');
    const [selectedAgentId, setSelectedAgentId] = useState(currentAgentId || null);
    const filteredUsers = users.filter((user) => user.name.toLowerCase().includes(search.toLowerCase()) ||
        user.email.toLowerCase().includes(search.toLowerCase()) ||
        user.role.toLowerCase().includes(search.toLowerCase()));
    const handleAssign = () => {
        if (selectedAgentId) {
            onAssign?.(selectedAgentId);
        }
    };
    return (_jsx("div", { className: "fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4", children: _jsxs("div", { className: "bg-white dark:bg-slate-900 rounded-xl shadow-xl max-w-lg w-full max-h-[90vh] overflow-hidden flex flex-col", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-700", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: "Assign Agent" }), _jsx("p", { className: "text-sm text-slate-500 dark:text-slate-400 mt-1", children: selectedCount === 1
                                        ? '1 challan selected'
                                        : `${selectedCount} challans selected` })] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors", children: _jsx(X, { className: "h-5 w-5 text-slate-500" }) })] }), _jsx("div", { className: "px-6 pt-4", children: _jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" }), _jsx("input", { type: "text", value: search, onChange: (e) => setSearch(e.target.value), placeholder: "Search by name, email, or role", className: "w-full pl-10 pr-4 py-2.5 text-sm bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-cyan-500 placeholder-slate-400 dark:placeholder-slate-500 text-slate-900 dark:text-white" })] }) }), _jsx("div", { className: "flex-1 overflow-y-auto px-6 py-4", children: filteredUsers.length === 0 ? (_jsxs("div", { className: "text-center py-8", children: [_jsx("div", { className: "w-12 h-12 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center mx-auto mb-3", children: _jsx(UserPlus, { className: "h-6 w-6 text-slate-400" }) }), _jsx("p", { className: "text-slate-900 dark:text-white font-medium mb-1", children: "No agents found" }), _jsx("p", { className: "text-sm text-slate-500 dark:text-slate-400", children: "Try a different search term" })] })) : (_jsx("div", { className: "space-y-2", children: filteredUsers.map((user) => (_jsx("button", { onClick: () => setSelectedAgentId(user.id), className: `w-full p-4 rounded-lg border-2 text-left transition-all ${selectedAgentId === user.id
                                ? 'border-cyan-500 bg-cyan-50 dark:bg-cyan-900/20'
                                : 'border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600 bg-white dark:bg-slate-800'}`, children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: `w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 text-sm font-medium ${selectedAgentId === user.id
                                            ? 'bg-cyan-600 text-white'
                                            : 'bg-slate-200 dark:bg-slate-700 text-slate-600 dark:text-slate-400'}`, children: user.name.charAt(0) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("div", { className: `font-medium ${selectedAgentId === user.id
                                                    ? 'text-cyan-900 dark:text-cyan-300'
                                                    : 'text-slate-900 dark:text-white'}`, children: user.name }), _jsx("div", { className: `text-sm ${selectedAgentId === user.id
                                                    ? 'text-cyan-700 dark:text-cyan-400'
                                                    : 'text-slate-500 dark:text-slate-400'}`, children: user.email }), _jsx("div", { className: `inline-block mt-1 px-2 py-0.5 rounded text-xs font-medium ${selectedAgentId === user.id
                                                    ? 'bg-cyan-100 dark:bg-cyan-900/40 text-cyan-700 dark:text-cyan-400'
                                                    : 'bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-400'}`, children: user.role })] }), selectedAgentId === user.id && (_jsx("div", { className: "flex-shrink-0", children: _jsx("div", { className: "w-5 h-5 rounded-full bg-cyan-600 flex items-center justify-center", children: _jsx("svg", { className: "w-3 h-3 text-white", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M5 13l4 4L19 7" }) }) }) }))] }) }, user.id))) })) }), _jsxs("div", { className: "flex justify-end gap-3 px-6 py-4 border-t border-slate-200 dark:border-slate-700", children: [_jsx("button", { onClick: onClose, className: "px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors", children: "Cancel" }), _jsx("button", { onClick: handleAssign, disabled: !selectedAgentId, className: "px-4 py-2 text-sm font-medium text-white bg-cyan-600 hover:bg-cyan-700 disabled:bg-slate-300 dark:disabled:bg-slate-700 disabled:cursor-not-allowed rounded-lg transition-colors", children: "Assign Agent" })] })] }) }));
}
