import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FileDown } from 'lucide-react';
import { MetricCard } from './MetricCard';
export function SubscribersTab({ data, onMetricClick, onExport, onExportMetric }) {
    const { summary, chartData } = data;
    return (_jsxs("div", { className: "px-6 pb-6 space-y-8", children: [
        _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4", children: Object.entries(summary).filter(([key]) => !['avgIncidentsPerSubscriber', 'avgSubscriptionValue', 'churnRate'].includes(key)).map(([key, metric]) => (_jsx(MetricCard, { metric: metric, onClick: () => onMetricClick?.(key) }, key))) }),
        _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [
            _jsxs("div", { className: "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6", children: [
                _jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h3", { className: "text-base font-semibold text-slate-900 dark:text-white", children: "Growth Trend" }), _jsx("button", { onClick: () => onExportMetric?.('csv', 'growthTrend'), className: "p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors", children: _jsx(FileDown, { className: "w-4 h-4 text-slate-600 dark:text-slate-400" }) })] }),
                _jsx("div", { className: "space-y-3", children: chartData.growthTrend.map((item) => (_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between text-sm mb-1", children: [_jsx("span", { className: "text-slate-600 dark:text-slate-400", children: item.month }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("span", { className: "text-emerald-600 dark:text-emerald-400 text-xs", children: ["+", item.new, " new"] }), _jsxs("span", { className: "text-rose-600 dark:text-rose-400 text-xs", children: ["-", item.churned, " churned"] }), _jsx("span", { className: "text-slate-900 dark:text-white font-semibold", children: item.active })] })] }), _jsx("div", { className: "h-8 bg-slate-100 dark:bg-slate-800 rounded overflow-hidden", children: _jsx("div", { className: "h-full bg-emerald-500 transition-all", style: { width: `${(item.active / 200) * 100}%` } }) })] }, item.month))) })
            ] }),
            _jsxs("div", { className: "bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6", children: [
                _jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h3", { className: "text-base font-semibold text-slate-900 dark:text-white", children: "Revenue Segments" }), _jsx("button", { onClick: () => onExportMetric?.('csv', 'revenueSegments'), className: "p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors", children: _jsx(FileDown, { className: "w-4 h-4 text-slate-600 dark:text-slate-400" }) })] }),
                _jsx("div", { className: "space-y-3", children: chartData.revenueSegments.map((item) => (_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between text-sm mb-1", children: [_jsx("span", { className: "text-slate-700 dark:text-slate-300", children: item.segment }), _jsxs("div", { className: "text-right", children: [_jsx("span", { className: "text-slate-900 dark:text-white font-semibold", children: item.count }), _jsxs("span", { className: "text-xs text-slate-500 dark:text-slate-400 ml-2", children: ["₹", (item.revenue / 100000).toFixed(1), "L"] })] })] }), _jsx("div", { className: "h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-emerald-500 rounded-full transition-all", style: { width: `${(item.count / 70) * 100}%` } }) })] }, item.segment))) })
            ] })
        ] })
    ] }));
}
