import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { CATEGORY_LABEL, CategoryIcon, formatDate, } from './KnowledgeBaseView';
export function KnowledgeBaseDetailModal({ entry, onClose, onEdit, onDelete, onDownload, }) {
    const [confirmDelete, setConfirmDelete] = useState(false);
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4", onClick: onClose, children: _jsxs("div", { className: "w-full max-w-3xl max-h-[90vh] overflow-hidden rounded-2xl bg-white dark:bg-slate-900 shadow-2xl flex flex-col", onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "flex items-start justify-between gap-4 px-6 py-5 border-b border-slate-200 dark:border-slate-700", children: [_jsxs("div", { className: "min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsxs("span", { className: "inline-flex items-center gap-1.5 rounded-full bg-slate-100 dark:bg-slate-800 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wider text-slate-600 dark:text-slate-300", children: [_jsx(CategoryIcon, { category: entry.category, className: "w-3.5 h-3.5" }), CATEGORY_LABEL[entry.category]] }), _jsx("span", { className: `inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${entry.status === 'published'
                                                ? 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400'
                                                : 'bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400'}`, children: entry.status })] }), _jsx("h2", { className: "text-xl font-bold text-slate-900 dark:text-white leading-tight", children: entry.title })] }), _jsx("button", { onClick: onClose, className: "p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-500 dark:text-slate-400", "aria-label": "Close", children: _jsx("svg", { className: "w-5 h-5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M6 18L18 6M6 6l12 12" }) }) })] }), _jsxs("div", { className: "flex items-center gap-4 px-6 py-3 bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-700 text-xs text-slate-500 dark:text-slate-400", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("svg", { className: "w-3.5 h-3.5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 1.75, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" }) }), entry.authorName] }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("svg", { className: "w-3.5 h-3.5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 1.75, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" }) }), "Updated ", formatDate(entry.updatedOn)] }), entry.tags.length > 0 && (_jsx("div", { className: "flex items-center gap-1.5 flex-wrap ml-auto", children: entry.tags.map((tag) => (_jsxs("span", { className: "inline-flex items-center rounded bg-slate-100 dark:bg-slate-800 px-2 py-0.5 text-[10px] font-medium text-slate-600 dark:text-slate-400", children: ["#", tag] }, tag))) }))] }), _jsxs("div", { className: "flex-1 overflow-auto px-6 py-6 space-y-6", children: [entry.description && (_jsx("div", { className: "kb-description text-sm text-slate-700 dark:text-slate-200 leading-relaxed", dangerouslySetInnerHTML: { __html: entry.description } })), _jsx(EntryContentBody, { entry: entry, onDownload: onDownload })] }), _jsx("style", { children: `
          .kb-description h1 { font-size: 1.5rem; font-weight: 700; margin: 0.5rem 0; line-height: 1.25; }
          .kb-description h2 { font-size: 1.25rem; font-weight: 700; margin: 0.5rem 0; line-height: 1.3; }
          .kb-description h3 { font-size: 1.1rem; font-weight: 600; margin: 0.4rem 0; line-height: 1.35; }
          .kb-description p { margin: 0.35rem 0; }
          .kb-description ul { list-style: disc; padding-left: 1.5rem; margin: 0.4rem 0; }
          .kb-description ol { list-style: decimal; padding-left: 1.5rem; margin: 0.4rem 0; }
          .kb-description li { margin: 0.15rem 0; }
          .kb-description a { color: rgb(8 145 178); text-decoration: underline; }
        ` }), _jsx("div", { className: "flex items-center justify-between gap-3 px-6 py-4 border-t border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50", children: confirmDelete ? (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-sm text-slate-700 dark:text-slate-300", children: "Delete this entry? Users won\u2019t see it in the app anymore." }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: () => setConfirmDelete(false), className: "px-3 py-1.5 rounded-md text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700", children: "Cancel" }), _jsx("button", { onClick: () => onDelete?.(entry.id), className: "px-3 py-1.5 rounded-md text-sm font-semibold bg-red-600 hover:bg-red-700 text-white", children: "Delete Entry" })] })] })) : (_jsxs(_Fragment, { children: [_jsxs("button", { onClick: () => setConfirmDelete(true), className: "inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20", children: [_jsx("svg", { className: "w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 1.75, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6M1 7h22M9 7V4a1 1 0 011-1h4a1 1 0 011 1v3" }) }), "Delete"] }), _jsxs("button", { onClick: () => onEdit?.(entry), className: "inline-flex items-center gap-1.5 px-4 py-1.5 rounded-md text-sm font-semibold bg-cyan-600 hover:bg-cyan-700 text-white", children: [_jsx("svg", { className: "w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 1.75, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" }) }), "Edit"] })] })) })] }) }));
}
function EntryContentBody({ entry, onDownload, }) {
    const content = entry.content;
    switch (content.kind) {
        case 'template': {
            const t = content.template;
            return (_jsx("div", { className: "space-y-4", children: _jsx("div", { className: "rounded-xl border border-slate-200 dark:border-slate-700 p-5 bg-slate-50 dark:bg-slate-800/50", children: _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "flex-shrink-0 w-12 h-14 rounded-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 flex flex-col items-center justify-center", children: [_jsx("svg", { className: "w-5 h-5 text-cyan-600 dark:text-cyan-400 -mt-0.5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 1.75, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" }) }), _jsx("span", { className: "text-[9px] font-bold text-slate-600 dark:text-slate-400 mt-0.5", children: t.fileFormat })] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "font-semibold text-slate-900 dark:text-white truncate", children: t.fileName }), _jsxs("p", { className: "text-xs text-slate-500 dark:text-slate-400 mt-0.5", children: [t.fileFormat, " \u00B7 ", t.fileSize] })] }), _jsxs("button", { onClick: () => onDownload?.(entry), className: "inline-flex items-center gap-2 rounded-lg bg-cyan-600 hover:bg-cyan-700 text-white text-sm font-semibold px-4 py-2", children: [_jsx("svg", { className: "w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" }) }), "Download Template"] })] }) }) }));
        }
        case 'faq':
            return (_jsx("div", { className: "space-y-3", children: content.items.map((item, i) => (_jsxs("details", { className: "group rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 overflow-hidden", open: i === 0, children: [_jsxs("summary", { className: "flex items-start justify-between gap-3 cursor-pointer px-4 py-3 hover:bg-slate-50 dark:hover:bg-slate-800/50 list-none", children: [_jsxs("div", { className: "flex items-start gap-3 min-w-0", children: [_jsx("span", { className: "mt-0.5 flex-shrink-0 w-6 h-6 rounded-full bg-cyan-100 dark:bg-cyan-900/40 text-cyan-700 dark:text-cyan-400 text-xs font-bold flex items-center justify-center", children: "Q" }), _jsx("span", { className: "font-semibold text-sm text-slate-900 dark:text-white leading-snug", children: item.question })] }), _jsx("svg", { className: "w-4 h-4 text-slate-400 flex-shrink-0 mt-1 transition-transform group-open:rotate-180", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M19 9l-7 7-7-7" }) })] }), _jsxs("div", { className: "px-4 pb-4 flex items-start gap-3 border-t border-slate-100 dark:border-slate-800 pt-3", children: [_jsx("span", { className: "mt-0.5 flex-shrink-0 w-6 h-6 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 text-xs font-bold flex items-center justify-center", children: "A" }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-300 leading-relaxed", children: item.answer })] })] }, i))) }));
        case 'guide':
            return (_jsx("ol", { className: "space-y-4", children: content.steps.map((step, i) => (_jsxs("li", { className: "flex items-start gap-4 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-4", children: [_jsx("div", { className: "flex-shrink-0 w-8 h-8 rounded-full bg-cyan-600 text-white text-sm font-bold flex items-center justify-center", children: i + 1 }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "font-semibold text-slate-900 dark:text-white mb-1", children: step.title }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-300 leading-relaxed", children: step.body })] })] }, i))) }));
        case 'checklist':
            return (_jsx("ul", { className: "space-y-2", children: content.items.map((item, i) => (_jsxs("li", { className: "flex items-start gap-3 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-4 py-3", children: [_jsx("span", { className: "flex-shrink-0 mt-1.5 w-2 h-2 rounded-full bg-cyan-500" }), _jsx("span", { className: "text-sm text-slate-700 dark:text-slate-200 leading-relaxed", children: item })] }, i))) }));
        case 'regulation': {
            const r = content.regulation;
            return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 p-4", children: _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Citation" }), _jsx("p", { className: "font-semibold text-slate-900 dark:text-white", children: r.citation })] }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Jurisdiction" }), _jsx("p", { className: "text-slate-700 dark:text-slate-200", children: r.jurisdiction })] })] }) }), _jsx("div", { className: "rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-4", children: _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200 leading-relaxed whitespace-pre-wrap", children: r.bodyText }) })] }));
        }
        case 'judgement': {
            const j = content.judgement;
            return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 p-4", children: [_jsx("p", { className: "text-base font-bold text-slate-900 dark:text-white mb-3", children: j.caseTitle }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-3 text-sm", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Court" }), _jsx("p", { className: "text-slate-800 dark:text-slate-200", children: j.court })] }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Decided On" }), _jsx("p", { className: "text-slate-800 dark:text-slate-200", children: formatDate(j.decidedOn) })] }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Citation" }), _jsx("p", { className: "text-slate-800 dark:text-slate-200", children: j.citation })] })] })] }), _jsxs("div", { className: "rounded-lg border-l-4 border-cyan-500 bg-cyan-50 dark:bg-cyan-900/20 px-4 py-3", children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-cyan-800 dark:text-cyan-400 mb-1", children: "Holding" }), _jsx("p", { className: "text-sm text-cyan-900 dark:text-cyan-200 font-medium leading-relaxed", children: j.holding })] }), _jsxs("div", { className: "rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-4", children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2", children: "Summary" }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200 leading-relaxed", children: j.summary })] })] }));
        }
        case 'circular': {
            const c = content.circular;
            return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/50 p-4 space-y-3", children: [_jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Issued By" }), _jsx("p", { className: "font-semibold text-slate-900 dark:text-white", children: c.issuedBy })] }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Issued On" }), _jsx("p", { className: "text-slate-800 dark:text-slate-200", children: formatDate(c.issuedOn) })] }), _jsxs("div", { className: "sm:col-span-2", children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-0.5", children: "Circular No." }), _jsx("p", { className: "font-mono text-slate-800 dark:text-slate-200", children: c.circularNumber })] })] }), _jsxs("div", { className: "pt-3 border-t border-slate-200 dark:border-slate-700", children: [_jsx("p", { className: "text-[10px] font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1", children: "Subject" }), _jsx("p", { className: "text-sm font-semibold text-slate-900 dark:text-white", children: c.subject })] })] }), _jsx("div", { className: "rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-4", children: _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-200 leading-relaxed whitespace-pre-wrap", children: c.body }) })] }));
        }
    }
}
