import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ProposalSidebar({ view, typeFilter, onViewChange, onTypeFilterChange, }) {
    return (_jsx("div", { className: "flex flex-col border-r border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 w-52", children: _jsxs("div", { className: "flex-1 py-4", children: [_jsxs("div", { className: "mb-2", children: [_jsx("div", { className: "px-4 py-2", children: _jsx("span", { className: "text-sm font-semibold text-slate-900 dark:text-white", children: "All Proposals" }) }), _jsxs("div", { className: "space-y-0.5 px-2", children: [_jsx("button", { onClick: () => onViewChange?.('all'), className: `w-full flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-all ${view === 'all'
                                        ? 'bg-cyan-50 dark:bg-cyan-900/20 text-cyan-700 dark:text-cyan-400'
                                        : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'}`, children: _jsx("span", { children: "All Proposals" }) }), _jsx("button", { onClick: () => onViewChange?.('my'), className: `w-full flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-all ${view === 'my'
                                        ? 'bg-cyan-50 dark:bg-cyan-900/20 text-cyan-700 dark:text-cyan-400'
                                        : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'}`, children: _jsx("span", { children: "My Proposals" }) })] })] }), _jsx("div", { className: "mx-4 my-3 border-t border-slate-200 dark:border-slate-700" }), _jsxs("div", { children: [_jsx("div", { className: "px-4 py-2", children: _jsx("span", { className: "text-sm font-semibold text-slate-900 dark:text-white", children: "Type" }) }), _jsxs("div", { className: "space-y-0.5 px-2", children: [_jsx("button", { onClick: () => onTypeFilterChange?.('all'), className: `w-full flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-all ${typeFilter === 'all'
                                        ? 'bg-cyan-50 dark:bg-cyan-900/20 text-cyan-700 dark:text-cyan-400'
                                        : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'}`, children: _jsx("span", { children: "All Types" }) }), _jsx("button", { onClick: () => onTypeFilterChange?.('Challan'), className: `w-full flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-all ${typeFilter === 'Challan'
                                        ? 'bg-cyan-50 dark:bg-cyan-900/20 text-cyan-700 dark:text-cyan-400'
                                        : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'}`, children: _jsx("span", { children: "Challan" }) }), _jsx("button", { onClick: () => onTypeFilterChange?.('DL'), className: `w-full flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-all ${typeFilter === 'DL'
                                        ? 'bg-cyan-50 dark:bg-cyan-900/20 text-cyan-700 dark:text-cyan-400'
                                        : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'}`, children: _jsx("span", { children: "DL" }) }), _jsx("button", { onClick: () => onTypeFilterChange?.('RC'), className: `w-full flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-all ${typeFilter === 'RC'
                                        ? 'bg-cyan-50 dark:bg-cyan-900/20 text-cyan-700 dark:text-cyan-400'
                                        : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'}`, children: _jsx("span", { children: "RC" }) })] })] })] }) }));
}
