import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { X, User, Search } from 'lucide-react';
export function AssignLeadModal({ leadId, leadName, currentAssignee, users, onAssign, onClose }) {
    const [selectedUser, setSelectedUser] = useState(currentAssignee || '');
    const [searchQuery, setSearchQuery] = useState('');
    const filteredUsers = users.filter(user => user.fullName.toLowerCase().includes(searchQuery.toLowerCase()) ||
        user.email.toLowerCase().includes(searchQuery.toLowerCase()));
    const handleAssign = () => {
        if (selectedUser) {
            onAssign(selectedUser);
        }
    };
    return (_jsx("div", { className: "fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 overflow-y-auto", children: _jsxs("div", { className: "bg-white dark:bg-slate-900 rounded-lg shadow-xl max-w-md w-full my-8", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-bold text-slate-900 dark:text-white", children: "Assign Lead" }), _jsx("p", { className: "text-sm text-slate-600 dark:text-slate-400 mt-0.5", children: leadName })] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors", children: _jsx(X, { className: "w-5 h-5 text-slate-500" }) })] }), _jsxs("div", { className: "px-6 py-4", children: [_jsxs("div", { className: "relative mb-4", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" }), _jsx("input", { type: "text", placeholder: "Search users...", value: searchQuery, onChange: e => setSearchQuery(e.target.value), className: "w-full pl-9 pr-3 py-2 bg-white dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg text-sm text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-cyan-500" })] }), _jsx("div", { className: "space-y-1 max-h-80 overflow-y-auto", children: filteredUsers.map(user => (_jsxs("button", { onClick: () => setSelectedUser(user.id), className: `w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${selectedUser === user.id
                                    ? 'bg-cyan-50 dark:bg-cyan-900/30 border-2 border-cyan-500'
                                    : 'bg-slate-50 dark:bg-slate-800/50 border-2 border-transparent hover:bg-slate-100 dark:hover:bg-slate-800'}`, children: [_jsx("div", { className: "w-10 h-10 bg-cyan-100 dark:bg-cyan-900/40 rounded-full flex items-center justify-center shrink-0", children: _jsx(User, { className: "w-5 h-5 text-cyan-600 dark:text-cyan-400" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("div", { className: "text-sm font-medium text-slate-900 dark:text-white truncate", children: user.fullName }), _jsx("div", { className: "text-xs text-slate-500 dark:text-slate-400 truncate", children: user.email }), _jsxs("div", { className: "text-xs text-slate-600 dark:text-slate-400 mt-0.5", children: [user.role, " \u2022 ", user.team] })] }), selectedUser === user.id && (_jsx("div", { className: "w-5 h-5 bg-cyan-600 rounded-full flex items-center justify-center shrink-0", children: _jsx("svg", { className: "w-3 h-3 text-white", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 3, d: "M5 13l4 4L19 7" }) }) }))] }, user.id))) })] }), _jsxs("div", { className: "flex items-center justify-end gap-3 px-6 py-4 border-t border-slate-200 dark:border-slate-800", children: [_jsx("button", { onClick: onClose, className: "px-4 py-2 bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300 rounded-lg font-medium hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors", children: "Cancel" }), _jsx("button", { onClick: handleAssign, disabled: !selectedUser, className: "px-4 py-2 bg-cyan-600 hover:bg-cyan-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-cyan-600", children: "Assign Lead" })] })] }) }));
}
