import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { MoreVertical, Eye, Edit2, UserX, UserCheck, Mail, Phone } from 'lucide-react';
export function LawyerRow({ lawyer, onView, onEdit, onDeactivate, onReactivate, }) {
    const [showActions, setShowActions] = useState(false);
    const isActive = lawyer.activityState === 'Active';
    const fullName = `${lawyer.firstName} ${lawyer.lastName}`;
    return (_jsxs("div", { className: "lg:grid lg:grid-cols-[80px_120px_1fr_200px_140px_140px_140px_100px_60px] gap-4 px-6 py-4 hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors group", children: [_jsxs("div", { className: "flex lg:block items-center gap-4 mb-4 lg:mb-0", children: [_jsxs("div", { className: "relative", children: [_jsx("img", { src: lawyer.photo, alt: fullName, className: "w-14 h-14 rounded-full object-cover ring-2 ring-slate-200 dark:ring-slate-700 group-hover:ring-cyan-500 dark:group-hover:ring-cyan-500 transition-all" }), _jsx("div", { className: `absolute -bottom-1 -right-1 w-5 h-5 rounded-full border-2 border-white dark:border-slate-900 ${isActive ? 'bg-emerald-500' : 'bg-slate-400'}` })] }), _jsxs("div", { className: "lg:hidden flex-1", children: [_jsx("div", { className: "font-semibold text-slate-900 dark:text-white", children: fullName }), _jsx("div", { className: "text-sm text-slate-600 dark:text-slate-400 font-mono", children: lawyer.lawyerId })] }), _jsxs("div", { className: "lg:hidden relative", children: [_jsx("button", { onClick: () => setShowActions(!showActions), className: "p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors", children: _jsx(MoreVertical, { className: "w-5 h-5 text-slate-600 dark:text-slate-400" }) }), showActions && (_jsxs(_Fragment, { children: [_jsx("div", { className: "fixed inset-0 z-10", onClick: () => setShowActions(false) }), _jsxs("div", { className: "absolute right-0 top-full mt-1 w-48 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg shadow-xl z-20 overflow-hidden", children: [_jsxs("button", { onClick: () => {
                                                    onView?.();
                                                    setShowActions(false);
                                                }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors", children: [_jsx(Eye, { className: "w-4 h-4" }), "View Profile"] }), _jsxs("button", { onClick: () => {
                                                    onEdit?.();
                                                    setShowActions(false);
                                                }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors", children: [_jsx(Edit2, { className: "w-4 h-4" }), "Edit"] }), isActive ? (_jsxs("button", { onClick: () => {
                                                    onDeactivate?.();
                                                    setShowActions(false);
                                                }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/20 transition-colors", children: [_jsx(UserX, { className: "w-4 h-4" }), "Deactivate"] })) : (_jsxs("button", { onClick: () => {
                                                    onReactivate?.();
                                                    setShowActions(false);
                                                }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-emerald-600 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-950/20 transition-colors", children: [_jsx(UserCheck, { className: "w-4 h-4" }), "Reactivate"] }))] })] }))] })] }), _jsx("div", { className: "hidden lg:flex items-center", children: _jsx("span", { className: "font-mono text-sm font-medium text-slate-900 dark:text-white px-3 py-1 bg-slate-100 dark:bg-slate-800 rounded-md", children: lawyer.lawyerId }) }), _jsxs("div", { className: "hidden lg:block", children: [_jsx("div", { className: "font-semibold text-slate-900 dark:text-white mb-1", children: fullName }), _jsxs("div", { className: "flex flex-col gap-1 text-sm text-slate-600 dark:text-slate-400", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Mail, { className: "w-3.5 h-3.5 flex-shrink-0" }), _jsx("span", { className: "truncate", children: lawyer.email })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Phone, { className: "w-3.5 h-3.5 flex-shrink-0" }), _jsx("span", { children: lawyer.mobile })] })] })] }), _jsxs("div", { className: "lg:hidden mb-4 space-y-1 text-sm", children: [_jsxs("div", { className: "flex items-center gap-2 text-slate-600 dark:text-slate-400", children: [_jsx(Mail, { className: "w-3.5 h-3.5 flex-shrink-0" }), _jsx("span", { className: "truncate", children: lawyer.email })] }), _jsxs("div", { className: "flex items-center gap-2 text-slate-600 dark:text-slate-400", children: [_jsx(Phone, { className: "w-3.5 h-3.5 flex-shrink-0" }), _jsx("span", { children: lawyer.mobile })] })] }), _jsx("div", { className: "mb-3 lg:mb-0 lg:flex lg:items-center", children: _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-slate-900 dark:text-white mb-0.5", children: lawyer.category }), _jsx("div", { className: "text-xs text-slate-500 dark:text-slate-500", children: lawyer.subCategory })] }) }), _jsx("div", { className: "mb-3 lg:mb-0 lg:flex lg:items-center", children: _jsx("span", { className: `inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold ${lawyer.onboardingStatus === 'Complete'
                        ? 'bg-emerald-100 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-400 ring-1 ring-emerald-600/20'
                        : 'bg-amber-100 dark:bg-amber-950/30 text-amber-700 dark:text-amber-400 ring-1 ring-amber-600/20'}`, children: lawyer.onboardingStatus }) }), _jsx("div", { className: "mb-3 lg:mb-0 lg:flex lg:items-center", children: _jsx("span", { className: `inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold ${lawyer.kycStatus === 'Verified'
                        ? 'bg-cyan-100 dark:bg-cyan-950/30 text-cyan-700 dark:text-cyan-400 ring-1 ring-cyan-600/20'
                        : lawyer.kycStatus === 'Pending'
                            ? 'bg-amber-100 dark:bg-amber-950/30 text-amber-700 dark:text-amber-400 ring-1 ring-amber-600/20'
                            : 'bg-red-100 dark:bg-red-950/30 text-red-700 dark:text-red-400 ring-1 ring-red-600/20'}`, children: lawyer.kycStatus }) }), _jsx("div", { className: "mb-3 lg:mb-0 lg:flex lg:items-center", children: _jsx("span", { className: `inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold ${isActive
                        ? 'bg-emerald-100 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-400 ring-1 ring-emerald-600/20'
                        : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 ring-1 ring-slate-600/20'}`, children: lawyer.activityState }) }), _jsx("div", { className: "mb-3 lg:mb-0 lg:flex lg:items-center", children: _jsx("span", { className: "text-sm text-slate-600 dark:text-slate-400", children: lawyer.source }) }), _jsxs("div", { className: "hidden lg:flex items-center justify-end relative", children: [_jsx("button", { onClick: () => setShowActions(!showActions), className: "p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors", children: _jsx(MoreVertical, { className: "w-5 h-5 text-slate-600 dark:text-slate-400" }) }), showActions && (_jsxs(_Fragment, { children: [_jsx("div", { className: "fixed inset-0 z-10", onClick: () => setShowActions(false) }), _jsxs("div", { className: "absolute right-0 top-full mt-1 w-48 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg shadow-xl z-20 overflow-hidden", children: [_jsxs("button", { onClick: () => {
                                            onView?.();
                                            setShowActions(false);
                                        }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors", children: [_jsx(Eye, { className: "w-4 h-4" }), "View Profile"] }), _jsxs("button", { onClick: () => {
                                            onEdit?.();
                                            setShowActions(false);
                                        }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors", children: [_jsx(Edit2, { className: "w-4 h-4" }), "Edit"] }), isActive ? (_jsxs("button", { onClick: () => {
                                            onDeactivate?.();
                                            setShowActions(false);
                                        }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/20 transition-colors", children: [_jsx(UserX, { className: "w-4 h-4" }), "Deactivate"] })) : (_jsxs("button", { onClick: () => {
                                            onReactivate?.();
                                            setShowActions(false);
                                        }, className: "w-full flex items-center gap-3 px-4 py-3 text-sm text-emerald-600 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-950/20 transition-colors", children: [_jsx(UserCheck, { className: "w-4 h-4" }), "Reactivate"] }))] })] }))] })] }));
}
