import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertCircle } from 'lucide-react';
function formatCurrency(amount) {
    return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
    }).format(amount);
}
function formatDateTime(dateString) {
    const date = new Date(dateString);
    return date.toLocaleString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
}
export function LinkedIncidentTab({ snapshot }) {
    if (!snapshot) {
        return (_jsx("div", { className: "p-6", children: _jsxs("div", { className: "text-center py-16", children: [_jsx("div", { className: "w-12 h-12 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center mx-auto mb-4", children: _jsx(AlertCircle, { className: "h-6 w-6 text-slate-400" }) }), _jsx("p", { className: "text-slate-900 dark:text-white font-medium mb-1", children: "No linked incident" }), _jsx("p", { className: "text-sm text-slate-500 dark:text-slate-400", children: "This dispute is linked to a subscriber or payment, not a specific incident." })] }) }));
    }
    return (_jsx("div", { className: "p-6", children: _jsxs("div", { className: "max-w-4xl mx-auto space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white mb-4", children: "Incident Details" }), _jsx("div", { className: "bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-6", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Incident ID" }), _jsx("p", { className: "text-sm font-mono font-semibold text-slate-900 dark:text-white", children: snapshot.incidentId })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Subscriber" }), _jsx("p", { className: "text-sm font-medium text-slate-900 dark:text-white", children: snapshot.subscriberName })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Vehicle Number" }), _jsx("p", { className: "text-sm font-mono text-slate-900 dark:text-white", children: snapshot.vehicleNumber })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Challan Number" }), _jsx("p", { className: "text-sm font-mono text-slate-900 dark:text-white", children: snapshot.challanNumber })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Type" }), _jsx("span", { className: `inline-flex items-center px-2 py-1 rounded text-xs font-medium ${snapshot.type === 'Contest'
                                                    ? 'bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400'
                                                    : 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400'}`, children: snapshot.type })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Outcome" }), _jsx("span", { className: `inline-flex items-center px-2 py-1 rounded text-xs font-medium ${snapshot.outcome === 'Settled'
                                                    ? 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400'
                                                    : snapshot.outcome === 'Not Settled'
                                                        ? 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400'
                                                        : snapshot.outcome === 'Refund'
                                                            ? 'bg-purple-50 dark:bg-purple-900/20 text-purple-700 dark:text-purple-400'
                                                            : 'bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400'}`, children: snapshot.outcome })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Assigned Lawyer" }), _jsx("p", { className: "text-sm text-slate-900 dark:text-white", children: snapshot.assignedLawyer || '—' })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Created On" }), _jsx("p", { className: "text-sm text-slate-900 dark:text-white", children: formatDateTime(snapshot.createdOn) })] }), snapshot.resolvedOn && (_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Resolved On" }), _jsx("p", { className: "text-sm text-slate-900 dark:text-white", children: formatDateTime(snapshot.resolvedOn) })] }))] }) })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white mb-4", children: "Financial Outcome" }), _jsx("div", { className: "bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-6", children: _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [_jsxs("div", { className: "bg-slate-50 dark:bg-slate-700/50 rounded-lg p-4", children: [_jsx("p", { className: "text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Challan Amount" }), _jsx("p", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: formatCurrency(snapshot.financialOutcome.challanAmount) })] }), _jsxs("div", { className: "bg-slate-50 dark:bg-slate-700/50 rounded-lg p-4", children: [_jsx("p", { className: "text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Amount Paid" }), _jsx("p", { className: "text-lg font-semibold text-slate-900 dark:text-white", children: formatCurrency(snapshot.financialOutcome.amountPaid) })] }), _jsxs("div", { className: "bg-slate-50 dark:bg-slate-700/50 rounded-lg p-4", children: [_jsx("p", { className: "text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Refund Due" }), _jsx("p", { className: `text-lg font-semibold ${snapshot.financialOutcome.refundDue > 0
                                                    ? 'text-red-600 dark:text-red-400'
                                                    : 'text-slate-900 dark:text-white'}`, children: formatCurrency(snapshot.financialOutcome.refundDue) })] }), _jsxs("div", { className: "bg-slate-50 dark:bg-slate-700/50 rounded-lg p-4", children: [_jsx("p", { className: "text-xs font-medium text-slate-500 dark:text-slate-400 mb-1", children: "Refund Status" }), _jsx("p", { className: "text-sm font-medium text-slate-900 dark:text-white", children: snapshot.financialOutcome.refundStatus })] })] }) })] }), _jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-slate-900 dark:text-white mb-4", children: "Timeline Summary" }), _jsx("div", { className: "bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-6", children: _jsx("div", { className: "space-y-3", children: snapshot.timelineSummary.map((entry, index) => (_jsxs("div", { className: "relative pl-8", children: [index < snapshot.timelineSummary.length - 1 && (_jsx("div", { className: "absolute left-[11px] top-6 bottom-0 w-0.5 bg-slate-200 dark:bg-slate-700" })), _jsx("div", { className: "absolute left-0 top-1.5 w-6 h-6 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center", children: _jsx("div", { className: "w-2 h-2 rounded-full bg-slate-400 dark:bg-slate-500" }) }), _jsx("p", { className: "text-sm text-slate-700 dark:text-slate-300 pb-3", children: entry })] }, index))) }) })] })] }) }));
}
