import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Menu, X } from 'lucide-react';
import { MainNav } from './MainNav';
import { UserMenu } from './UserMenu';
export function AppShell({ children, navigationItems, user, breadcrumbs, onNavigate, onLogout, }) {
    const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
    const [isSidebarHovered, setIsSidebarHovered] = useState(false);
    // Sidebar is collapsed by default, expands on hover
    const isSidebarCollapsed = !isSidebarHovered;
    return (_jsxs("div", { className: "flex h-screen bg-slate-50 dark:bg-slate-950", children: [_jsxs("aside", { className: `hidden lg:flex lg:flex-col border-r border-zinc-800 transition-all duration-300 ${isSidebarCollapsed ? 'lg:w-16' : 'lg:w-60'}`, style: { backgroundColor: '#212121' }, onMouseEnter: () => setIsSidebarHovered(true), onMouseLeave: () => setIsSidebarHovered(false), children: [_jsx("div", { className: `flex items-center h-16 border-b border-zinc-800 ${isSidebarCollapsed ? 'justify-center px-2' : 'px-4'}`, children: isSidebarCollapsed ? (_jsx("span", { className: "text-xl font-bold text-cyan-400", children: "L" })) : (_jsx("img", { src: "/logo.png", alt: "Lawyered", className: "h-8" })) }), _jsx(MainNav, { items: navigationItems, onNavigate: onNavigate, isCollapsed: isSidebarCollapsed, darkMode: true })] }), isMobileMenuOpen && (_jsxs(_Fragment, { children: [_jsx("div", { className: "fixed inset-0 bg-zinc-950/50 z-40 lg:hidden", onClick: () => setIsMobileMenuOpen(false) }), _jsxs("aside", { className: "fixed inset-y-0 left-0 w-64 bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-800 z-50 lg:hidden", children: [_jsxs("div", { className: "flex items-center justify-between h-16 px-6 border-b border-slate-200 dark:border-slate-800", children: [_jsx("h1", { className: "text-xl font-bold text-slate-900 dark:text-white", children: "Admin Panel" }), _jsx("button", { onClick: () => setIsMobileMenuOpen(false), className: "p-2 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white", children: _jsx(X, { className: "w-5 h-5" }) })] }), _jsx(MainNav, { items: navigationItems, onNavigate: (href) => {
                                    onNavigate?.(href);
                                    setIsMobileMenuOpen(false);
                                } })] })] })), _jsxs("div", { className: "flex-1 flex flex-col overflow-hidden", children: [_jsxs("header", { className: "flex items-center justify-between h-16 px-4 lg:px-6 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800", children: [_jsx("div", { className: "flex items-center space-x-4 flex-1", children: _jsx("button", { onClick: () => setIsMobileMenuOpen(true), className: "p-2 text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white lg:hidden", children: _jsx(Menu, { className: "w-6 h-6" }) }) }), user && _jsx(UserMenu, { user: user, onLogout: onLogout })] }), _jsx("main", { className: "flex-1 overflow-auto", children: children })] }), _jsx("nav", { className: "fixed bottom-0 left-0 right-0 bg-white dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 lg:hidden z-30", children: _jsx("div", { className: "flex items-center justify-around h-16", children: navigationItems.slice(0, 5).map((item) => (_jsxs("button", { onClick: () => onNavigate?.(item.href), className: `flex flex-col items-center justify-center flex-1 h-full space-y-1 ${item.isActive
                            ? 'text-cyan-600 dark:text-cyan-400'
                            : 'text-slate-600 dark:text-slate-400'}`, children: [item.icon && _jsx(item.icon, { className: "w-5 h-5" }), _jsx("span", { className: "text-xs", children: item.label })] }, item.href))) }) })] }));
}
